github: [metadata]

remote_theme: eclipsefdn/jekyll-theme-eclipsefdn
#theme: jekyll-theme-eclipsefdn # for local execution

title: [Eclipse Soteria]
description: [Eclipse EE4J implementation of Jakarta Standard Tag Library]

links:
  source: https://github.com/eclipse-ee4j/jstl-api
  javadocs: docs/api/
  issues_url: site.github.issues_url
  download: https://github.com/eclipse-ee4j/jstl-api/releases
  mailinglist: https://accounts.eclipse.org/mailing-list/jstl-dev
  # faq: FAQ

include:
  - LICENSE.md
  - CONTRIBUTING.md
